let projectData = [{
    id: 1,
    name: "Lab 1",
    date: "9/19/20",
    url: "http://lab1.natehroylance.com/",
    alt: "image of Lab 1",
    image: 'lab1.jpg',
  },
  {
    id: 2,
    name: "Lab 2",
    date: "10/10/20",
    url: "http://lab2.natehroylance.com/",
    alt: "image of Lab 2",
    image: 'lab2.jpg',
  },
  {
    id: 3,
    name: "Lab 3a",
    date: "10/24/20",
    url: "http://lab3a.natehroylance.com/",
    alt: "image of Lab 3a",
    image: 'lab3a.jpg',
  },
  {
    id: 4,
    name: "Lab 3b",
    date: "10/30/20",
    url: "http://motherearth.natehroylance.com/",
    alt: "image of Lab 3b",
    image: 'lab3b.jpg',
  },
  {
    id: 5,
    name: "CProject 1",
    date: "9/26/20",
    url: "http://cp1.natehroylance.com/",
    alt: "image of cp 1",
    image: 'cp1.jpg',
  },
  {
    id: 6,
    name: "CProject 2",
    date: "10/17/20",
    url: "http://cp2.natehroylance.com/",
    alt: "image of cp 2",
    image: 'cp2.jpg',
  },
  {
    id: 7,
    name: "1st Game",
    date: "11/3/20",
    url: "http://game1.natehroylance.com/",
    alt: "image of game 1",
    image: 'game1.jpg',
  },
  {
    id: 8,
    name: "2nd Game",
    date: "11/6/20",
    url: "http://game2.natehroylance.com/",
    alt: "image of game 2",
    image: 'game2.jpg',
  },
]

export default projectData;
